"""Render a sectioned Markdown newsletter from clustered + summarised stories."""

from __future__ import annotations

import logging
import re
from datetime import UTC, datetime
from pathlib import Path

from finxnews.models import StoryCluster

logger = logging.getLogger(__name__)

_MD_SPECIAL = re.compile(r"([\\`*_\[\]()#+\-.!|{}])")


def _esc(text: str) -> str:
    """Escape special Markdown characters in tweet text."""
    return _MD_SPECIAL.sub(r"\\\1", text)


def _tweet_link(username: str, tweet_id: str) -> str:
    return f"https://x.com/{username}/status/{tweet_id}"


def render(
    clusters: list[StoryCluster],
    daily_tldr: str,
    profile: str = "",
    query_summary: str = "",
) -> str:
    """Return a full Markdown newsletter string."""
    now = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
    title = profile.title() if profile else "Finance"
    parts: list[str] = []

    # ── Header ──────────────────────────────────────────────────────────
    parts.append(f"# {title} Digest — {now}\n")
    if query_summary:
        parts.append(f"_Coverage: {query_summary}_\n")

    # ── Daily TL;DR ─────────────────────────────────────────────────────
    parts.append("## Daily TL;DR\n")
    parts.append(daily_tldr + "\n")

    # ── Per-story sections ──────────────────────────────────────────────
    parts.append("---\n")
    parts.append("## Top Stories\n")

    for i, cluster in enumerate(clusters, 1):
        parts.append(f"### {i}. {cluster.label}\n")

        if cluster.summary:
            parts.append(f"{cluster.summary}\n")

        if cluster.bullets:
            for bullet in cluster.bullets:
                parts.append(f"- {bullet}")
            parts.append("")  # blank line

        # Source tweets
        parts.append("**Sources:**\n")
        for tweet in cluster.tweets[:5]:
            link = _tweet_link(tweet.author_username, tweet.tweet_id)
            # Truncate long tweets in the listing
            preview = _esc(tweet.text[:140])
            if len(tweet.text) > 140:
                preview += "…"
            metrics = tweet.metrics
            stats = (
                f"❤️{metrics.like_count} "
                f"🔁{metrics.retweet_count} "
                f"💬{metrics.reply_count}"
            )
            parts.append(f"- [@{tweet.author_username}]({link}): {preview} ({stats})")
        parts.append("")  # blank line

    # ── Footer ──────────────────────────────────────────────────────────
    parts.append("---\n")
    parts.append(f"_Generated by finxnews v0.1 at {now}_\n")

    return "\n".join(parts)


def write_newsletter(
    clusters: list[StoryCluster],
    daily_tldr: str,
    output_dir: Path,
    profile: str = "",
    query_summary: str = "",
) -> Path:
    """Render and write a timestamped newsletter to *output_dir*.

    Output path: ``<output_dir>/newsletter-YYYYmmdd-HHMMSSZ.md``
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    md = render(clusters, daily_tldr, profile=profile, query_summary=query_summary)
    ts = datetime.now(UTC).strftime("%Y%m%d-%H%M%SZ")
    filename = f"newsletter-{ts}.md"
    out_path = output_dir / filename
    out_path.write_text(md, encoding="utf-8")
    logger.info("Wrote newsletter to %s (%d chars)", out_path, len(md))
    return out_path
